# Generated by Django 5.0.2 on 2025-07-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bagues', 'Bagues'), ('colliers', 'Colliers'), ('bracelets', 'Bracelets'), ('boucles', "Boucles d'oreilles"), ('sacs', 'Sacs'), ('autres', 'Autres accessoires')], default='autres', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Remise en pourcentage'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Nouveau produit'),
        ),
    ]
